import type { ParagraphChild } from 'docx';
import type { IssueDecision, ReviewIssue } from '@/lib/types';
import type { AppliedEdit } from '@/lib/author-editing';
import { composeWorkingText } from '@/lib/author-editing';

export interface AuthorDocxExportOptions {
  mode: 'tracked' | 'clean';
  projectTitle: string;
  targetJournal?: string;
  sectionLabel?: string;
  sourceText: string;
  edits: AppliedEdit[];
  issues: ReviewIssue[];
  decisions: Record<string, IssueDecision>;
}

function safeFileStem(value: string) {
  return (value || 'scholarforge-manuscript')
    .trim()
    .replace(/[\\/:*?"<>|]+/g, '-')
    .replace(/\s+/g, '-')
    .slice(0, 90) || 'scholarforge-manuscript';
}

function paragraphRanges(source: string) {
  const ranges: Array<{ text: string; start: number; end: number }> = [];
  const separator = /\n{2,}/g;
  let start = 0;
  let match: RegExpExecArray | null;
  while ((match = separator.exec(source))) {
    ranges.push({ text: source.slice(start, match.index), start, end: match.index });
    start = match.index + match[0].length;
  }
  ranges.push({ text: source.slice(start), start, end: source.length });
  return ranges;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function exportAuthorDocx(options: AuthorDocxExportOptions) {
  const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    InsertedTextRun,
    DeletedTextRun,
    HeadingLevel,
    PageBreak,
  } = await import('docx');

  const author = 'ScholarForge OS / Author';
  const revisionDate = new Date().toISOString();
  const orderedEdits = [...options.edits].sort((a, b) => a.start - b.start);
  const workingText = composeWorkingText(options.sourceText, orderedEdits);
  let revisionId = 1;

  const titleParagraphs = [
    new Paragraph({ text: options.projectTitle || 'ScholarForge manuscript', heading: HeadingLevel.TITLE }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Generated by ScholarForge OS v1.2', bold: true }),
        new TextRun({ text: ` · ${options.mode === 'tracked' ? 'Word tracked changes' : 'Clean author manuscript'}` }),
      ],
    }),
    new Paragraph({ text: `Target journal: ${options.targetJournal || 'Not specified'}` }),
    new Paragraph({ text: `Section: ${options.sectionLabel || 'General manuscript section'}` }),
    new Paragraph({ text: `Applied suggestions: ${orderedEdits.length}` }),
    new Paragraph({ children: [new PageBreak()] }),
  ];

  const manuscriptParagraphs = options.mode === 'clean'
    ? paragraphRanges(workingText).map((range) => new Paragraph({
        children: [new TextRun({ text: range.text || ' ' })],
        spacing: { after: 180, line: 360 },
      }))
    : paragraphRanges(options.sourceText).map((range) => {
        const paragraphEdits = orderedEdits.filter((edit) => edit.start >= range.start && edit.end <= range.end);
        const children: ParagraphChild[] = [];
        let cursor = range.start;

        for (const edit of paragraphEdits) {
          if (edit.start > cursor) children.push(new TextRun({ text: options.sourceText.slice(cursor, edit.start) }));
          children.push(new DeletedTextRun({
            id: revisionId++,
            author,
            date: revisionDate,
            text: options.sourceText.slice(edit.start, edit.end),
          }));
          children.push(new InsertedTextRun({
            id: revisionId++,
            author,
            date: revisionDate,
            text: edit.revised,
          }));
          cursor = edit.end;
        }
        if (cursor < range.end) children.push(new TextRun({ text: options.sourceText.slice(cursor, range.end) }));
        if (!children.length) children.push(new TextRun({ text: range.text || ' ' }));
        return new Paragraph({ children, spacing: { after: 180, line: 360 } });
      });

  const decisionParagraphs = [
    new Paragraph({ children: [new PageBreak()] }),
    new Paragraph({ text: 'Author Decision Appendix', heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ text: 'This appendix records every AI suggestion and the author-side workflow state. Suggestions that could not be uniquely anchored were not inserted into the manuscript.' }),
    ...options.issues.flatMap((issue, index) => {
      const decision = options.decisions[issue.id] || (orderedEdits.some((edit) => edit.issueId === issue.id) ? 'accepted' : 'pending');
      return [
        new Paragraph({
          children: [
            new TextRun({ text: `${index + 1}. ${issue.category}`, bold: true }),
            new TextRun({ text: ` · ${issue.severity.toUpperCase()} · ${decision}` }),
          ],
        }),
        new Paragraph({ text: `Location: ${issue.location || 'Not specified'}` }),
        new Paragraph({ text: `Original: ${issue.original || 'Not supplied'}` }),
        new Paragraph({ text: `Suggestion: ${issue.revised || 'Author action required'}` }),
        new Paragraph({ text: `Reason: ${issue.reason}` }),
      ];
    }),
  ];

  const doc = new Document({
    creator: 'ScholarForge OS',
    title: options.projectTitle || 'ScholarForge manuscript',
    description: 'Scientific manuscript generated from author-reviewed ScholarForge suggestions.',
    features: { trackRevisions: options.mode === 'tracked' },
    styles: {
      default: {
        document: {
          run: { font: 'Times New Roman', size: 24 },
          paragraph: { spacing: { line: 360 } },
        },
      },
    },
    sections: [{
      properties: {
        page: {
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children: [...titleParagraphs, ...manuscriptParagraphs, ...decisionParagraphs],
    }],
  });

  const blob = await Packer.toBlob(doc);
  const suffix = options.mode === 'tracked' ? 'tracked-changes' : 'clean-manuscript';
  downloadBlob(blob, `${safeFileStem(options.projectTitle)}-${suffix}.docx`);
}
