import { NextResponse } from 'next/server';

export function GET() {
  const authConfigured = Boolean(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  );

  return NextResponse.json({
    status: 'ok',
    service: 'ScholarForge OS',
    version: '1.3.5',
    ui: 'focused-research-writing-workspace',
    provider: 'Alibaba Cloud Model Studio',
    model: process.env.DASHSCOPE_MODEL || 'qwen-plus',
    workflow: 'task-aware-parallel-multi-agent',
    specialists: 4,
    taskTypes: ['translate', 'polish', 'precheck', 'review-response'],
    reviewSections: 7,
    reviewModes: 3,
    terminologyLocks: true,
    authorDecisionStates: 4,
    safeIssueApply: true,
    issueAnchorModes: ['exact', 'whitespace-normalized'],
    overlappingEditProtection: true,
    authorUndoRedo: true,
    docxCleanExport: true,
    docxTrackedChangesExport: true,
    originalDocxPackageRetention: 'browser-indexeddb',
    originalDocxPatchExport: true,
    originalDocxPreservedParts: ['styles', 'media', 'tables', 'equations', 'headers', 'footers', 'relationships'],
    originalDocxPatchSkippedStructures: ['tables', 'equations', 'fields', 'hyperlinks', 'comments', 'existing-revisions', 'complex-inline-content'],
    documentIngestion: true,
    documentFormats: ['docx', 'text-based-pdf'],
    documentParsingLocation: 'browser',
    documentSectionDetection: true,
    documentChunkLimit: 12000,
    scannedPdfOcr: false,
    localReviewHistory: true,
    canonicalHistorySurface: 'project-hub',
    historyPreviewViews: ['output', 'issues', 'trace'],
    duplicateWorkspaceHistoryEntries: false,
    projectHub: true,
    workflowTemplates: 4,
    localWorkspaceBackup: true,
    localWorkspaceRestore: true,
    cloudWorkspaceSupported: true,
    cloudWorkspaceConfigured: authConfigured,
    cloudWorkspaceMigration: 'supabase/migrations/20260730_cloud_workspace.sql',
    cloudWorkspaceIsolation: 'Supabase RLS by auth.uid()',
    localFallback: 'guest-session',
    workspaceAccess: 'authenticated-session-required',
    accountModes: ['supabase', 'guest'],
    guestAccess: true,
    localDemoAccounts: false,
    productionDependencyAudit: 'blocking-high-severity',
    dependencyOverrides: {
      postcss: '^8.5.22',
      sharp: '^0.35.3',
    },
    codeAudit: {
      unusedLocals: true,
      unusedParameters: true,
      obsoleteStyleOverridesRemoved: true,
      localBackupValidation: true,
      originalDocxRollback: true,
      redundantDemoAuthRemoved: true,
      duplicateHistoryNavigationRemoved: true,
      hiddenHistoryImplementationRemoved: true,
      duplicateWorkbenchControlsRemoved: true,
      semanticStyleLayers: ['history-preview.css', 'workbench-responsive.css'],
      removedStyleLayers: ['v06-fixes.css', 'v133.css'],
    },
    modelStudioConfigured: Boolean(process.env.DASHSCOPE_API_KEY),
    authProvider: 'Supabase Auth',
    authConfigured,
    timestamp: new Date().toISOString(),
  });
}
